# This file contains the configuration for the Jenkins Helm chart.
controller:
  image:
    registry: docker.io
    repository: ankitofficial1821/jenkins-with-tools
    tag: "latest"
  serviceType: LoadBalancer
  servicePort: 80
  imagePullPolicy: "Always"
  javaOpts: "-Djenkins.install.runSetupWizard=false -Djenkins.CASC_JENKINS_CONFIG=/var/jenkins_home/casc_configs -Djenkins.model.Jenkins.logStartupPerformance=true"

  containerSecurityContext:
    privileged: true
    allowPrivilegeEscalation: true

  securityContext:
    enabled: true
    fsGroup: 1000
    runAsUser: 1000


  additionalVolumes:
    - name: kubeconfig
      secret:
        secretName: jenkins-kubeconfig

  additionalVolumeMounts:
    - name: kubeconfig
      mountPath: /var/jenkins_home/.kube

  installPlugins:
    - kubernetes:1.30.1
    - configuration-as-code:latest
    - workflow-aggregator:2.6
    - git:5.7.0
    - docker-workflow:1.28
    - workflow-job:latest
    - nodejs:1.6.0
    - blueocean:1.25.3
    - job-dsl:1.81
    - git-client:latest

  initializationScripts:
    init-hook: |
      println("Waiting for plugins to install...")

  javaOpts: "-Xmx512m"

  JCasC:
    enabled: true
    defaultConfig: false
    configScripts:
      jcasc-config: |
        jenkins:
          systemMessage: "Jenkins configured as code!"
          numExecutors: 2
          mode: NORMAL
          scmCheckoutRetryCount: 2
          securityRealm:
            local:
              allowsSignup: false
              users:
                - id: "admin"
                  password: "admin"
          authorizationStrategy:
            loggedInUsersCanDoAnything:
              allowAnonymousRead: false
          crumbIssuer:
            excludeClientIPFromCrumb: false
            proxyCompatability: true

        jobs:
          - script: >
              pipelineJob('Nodejs-CI-CD') {
                definition {
                  cpsScm {
                    scm {
                      git {
                        remote {
                          url('https://github.com/Ankitdevops18/nodejs-sample.git')
                        }
                        branches('master')
                      }
                    }
                    scriptPath('Jenkinsfile')
                  }
                }
                triggers {
                  gitHubPushTrigger {}
                }
              }