# This file contains the configuration for the Jenkins Helm chart.
controller:
  image:
    registry: docker.io
    repository: ankitofficial1821/jenkins-with-tools
    tag: "latest"
  serviceType: LoadBalancer
  servicePort: 80
  imagePullPolicy: "Always"
  additionalVolumes:
    - name: kubeconfig
      secret:
        secretName: jenkins-kubeconfig
  additionalVolumeMounts:
    - name: kubeconfig
      mountPath: /var/jenkins_home/.kube
  installPlugins:
    - kubernetes:1.30.1
    - workflow-aggregator:2.6
    - git:5.7.0
    - docker-workflow:1.28
    - nodejs:1.5.1
    - workflow-job:latest
    - blueocean:1.25.3

  javaOpts: "-Xmx512m"

  JCasC:
    configScripts:
      jcasc-config: |
        {{ .Files.Get "jenkins/jenkins.yaml" }}
